### PR TITLE
Adds dropwizard metrics, overhaul of how application is initialized

### PR DESCRIPTION
**Pull request by hanswesterbeek**
Migrated to use of play 2.4-recommended dependency injection, 'compile-time' variant. That means far less static classes, greater testability and the ability to keep upgrading Play, as they are sure to deprecate '`object`' components.

Did **not** use the run-time variant (which relies on Guice) because it is unneeded and requires programmers to learn another framework.

**Note:** Considering the fact that the init-overhaul is so fundamental, a full re-test of the app is required before merging this branch. I have processed the 'first' sip.zip with success. Works on my machine :)

### CODE REVIEW

**Comment by kiivihal** [comment]
I have been testing this pull-request and ran into an issue during the initial PMH harvest:

* error in the interface: ` While Harvesting, failure: play.api.libs.ws.WSAPI`
* stacktrace:
```
java.lang.InstantiationException: play.api.libs.ws.WSAPI
    at java.lang.Class.newInstance(Class.java:427)
    at play.api.inject.NewInstanceInjector$.instanceOf(Injector.scala:49)
    at play.api.inject.SimpleInjector$$anonfun$instanceOf$1.apply(Injector.scala:85)
    at scala.collection.MapLike$class.getOrElse(MapLike.scala:128)
    at scala.collection.AbstractMap.getOrElse(Map.scala:59)
    at play.api.inject.SimpleInjector.instanceOf(Injector.scala:85)
    at play.api.inject.SimpleInjector.instanceOf(Injector.scala:80)
    at play.api.Application$$anonfun$instanceCache$1.apply(Application.scala:235)
    at play.api.Application$$anonfun$instanceCache$1.apply(Application.scala:235)
    at play.utils.InlineCache.fresh(InlineCache.scala:69)
    at play.utils.InlineCache.apply(InlineCache.scala:55)
    at play.api.libs.ws.WS$.wsapi(WS.scala:94)
    at play.api.libs.ws.WS$.url(WS.scala:121)
    at harvest.Harvesting$class.fetchPMHPage(Harvesting.scala:178)
    at harvest.Harvester.fetchPMHPage(Harvester.scala:48)
    at harvest.Harvester$$anonfun$receive$1$$anonfun$applyOrElse$3.apply$mcV$sp(Harvester.scala:161)
    at nxutil.Utils$.actorWork(Utils.scala:22)
    at harvest.Harvester$$anonfun$receive$1.applyOrElse(Harvester.scala:158)
    at akka.actor.Actor$class.aroundReceive(Actor.scala:467)
    at harvest.Harvester.aroundReceive(Harvester.scala:48)
    at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
    at akka.actor.ActorCell.invoke(ActorCell.scala:487)
    at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
    at akka.dispatch.Mailbox.run(Mailbox.scala:220)
    at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)
    at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
    at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
    at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
    at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.NoSuchMethodException: play.api.libs.ws.WSAPI.&lt;init&gt;()
    at java.lang.Class.getConstructor0(Class.java:3082)
    at java.lang.Class.newInstance(Class.java:412)
... 28 more
```

**Comment by hanswesterbeek** [comment]
How to reproduce?

**Comment by hanswesterbeek** [comment]
Fixed the obvious errors but would still like to be able to reproduce... Guess I need a OAI-PMH url?

**Comment by kiivihal** [comment]
I have verified that the harvesting and incremental harvesting now works again. I will merge this pull-request.

**Pull request merged**
